### ISSUE TITLE
`*` filter.

### ISSUE THREAD

**Issue by jangaraj** [monitoringartist/grafana-aws-cloudwatch-dashboards#101]
> Could you provide dashboard example, please? I'm curious about that `*` filter.

Hi jan 
I'm trying to get data in grafana for route53 and for aws billing but in both of them I'm getting no data and for route53 I'm getting this error too (InvalidParameter: 2 validation error(s) found. - minimum field size of 1, GetMetricDataInput.MetricDataQueries[0].MetricStat.Metric.Dimensions[0].Value. - minimum field size of 1, GetMetricDataInput.MetricDataQueries[1].MetricStat.Metric.Dimensions[0].Value.)
Can you please help me to solve it will be much appreciated 
Thankyou guys..
@jangaraj

_Originally posted by @kachhela57 in https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/issues/72#issuecomment-831158028_

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/tree/master/aws-certificate-manager uses All (`*` filter). Make sure you have proper permissions in used IAM role/user and variables - see readme:

> Please set your dashboard variables (Region, ...) after dashboard import. Empty dashboard variables are reason of initial "Unable to call AWS API" or "Metric request error" error.

**Comment by jangaraj** [comment]
I'm closing, because this doesn't look like a dashboard issue, but your Grafana config problem. Unfortunately, Grafana support is not in the scope of this project. I gave you general recommendation in the previous comment. If you need more, please contact your Grafana/AWS support.

**Comment by kachhela57** [comment]
> I'm closing, because this doesn't look like a dashboard issue, but your Grafana config problem. Unfortunately, Grafana support is not in the scope of this project. I gave you general recommendation in the previous comment. If you need more, please contact your Grafana/AWS support.

Hi Jan,
I have tried every possible value but still no data is reflecting i have attached some screenshots if you can help me 
Thankyou for your support
![Screenshot from 2021-05-03 18-42-42](https://user-images.githubusercontent.com/70208439/116881119-812c9880-ac40-11eb-832e-60cd5f3e95e0.png)
![Screenshot from 2021-05-03 18-43-10](https://user-images.githubusercontent.com/70208439/116881230-a02b2a80-ac40-11eb-9a6c-70e8cf62a8b6.png)

**Comment by jangaraj** [comment]
Sorry, I'm not a free support.
