### ISSUE TITLE
feature: links to AWS Dashboards

### ISSUE THREAD

**Issue by strowi** [monitoringartist/grafana-aws-cloudwatch-dashboards#104]
Hi,

looking at these grafana-dashboards i often find myself wanting to check/modify/... the resources etc. directly in aws.
How about adding the respective links on your dashboards?

E.g.:
Dasboard: AWS EC2 
Link: https://console.aws.amazon.com/ec2/v2/home
Not sure though if this works for all dashboards..

Maybe those can even be constructed by adding the {{region}} etc..?

regards,
strowi

**Comment by jangaraj** [comment]
Thanks. I would say it is possible, but generic implementation is not easy. The main problem is that dashboard may show CloudWatch data from the AWS account, where Grafana user doesn't have AWS console access or where their current AWS console session is not opened. That may lead to user confusions - why Grafana dashboard data (e.g. EC2 instance IDs) are not the same as data in the AWS console. 
So I wouldn't prefer any AWS Console links in dashboards.
