### ISSUE TITLE
Metric request error in AWS Cognito grafana template 

### ISSUE THREAD

**Issue by s1mrankaur** [monitoringartist/grafana-aws-cloudwatch-dashboards#105]
I am able to select user pools in the select box. I always see "None" for pool clients and IdentityProvider (which is okay).

But I am constantly seeing - Metric request error for all 4 graphs in Cognito grafana template. How can I fix this?
```

Metric request error
Object
status:500
statusText:""
data:Object
message:"Metric request error"
config:Object
method:"POST"
url:"api/ds/query"
data:Object
retry:0
headers:Object
hideFromInspector:false
message:"Metric request e
```rror"

**Comment by jangaraj** [comment]
The latest dashboard version has `All` (*) as the default value for the IdentityProvider variable, so it shouldn't be failing now.
