### ISSUE TITLE
AWS Billing Dashboard show 600.00 instead of 60.00 on AWS cost console

### ISSUE THREAD

**Issue by edgarcolquecohley** [monitoringartist/grafana-aws-cloudwatch-dashboards#106]
Hello,
  first of all, those dashboard are Great, and maybe this issue is because I am doing something wrong.
  
 This is an example os my issue:
 
![image](https://user-images.githubusercontent.com/81574945/129080848-8a73cbb6-b93b-4222-9b58-42b3f434285b.png)

and from AWS console
![image](https://user-images.githubusercontent.com/81574945/129080715-6085ee9a-d54c-42ac-8a5d-965b69ca24c4.png)

**Comment by jangaraj** [comment]
Billing dashboard from this repo doesn't provide `Daily Spend by Account` panel. It seems to be your own customization, so unfortunately it can't be supported here. I would recommend to ask [community](https://community.grafana.com/).

**Comment by edgarcolquecohley** [comment]
Do you support this dashboard?
https://grafana.com/grafana/dashboards/13514

**Comment by jangaraj** [comment]
No. `Italo Santos` is the author and he just copied our description.
![image](https://user-images.githubusercontent.com/1182932/129087747-1a1b5352-11c0-4a5a-994a-9828501fd259.png)
