### ISSUE TITLE
AWS Billing metric returns empty array

### ISSUE THREAD

**Issue by mitul-srashtasoft** [monitoringartist/grafana-aws-cloudwatch-dashboards#108]
![Capture](https://user-images.githubusercontent.com/73469192/132345983-551b7def-2aeb-474d-ac35-12c51d26b360.PNG)

Not getting data.

**Comment by jangaraj** [comment]
Dashboard doesn't generate data. It only visualizes what you have in your CloudWatch, so it isn't a issue of the dashboard. Please consult issue with your AWS support/admin/... (blind guess: you don't have billing alarms, so that metric is not generated).

**Comment by mitul-srashtasoft** [comment]
Got it, Thanks @jangaraj.
