### ISSUE TITLE
Could create dashboard for DynamoDB ? 

### ISSUE THREAD

**Issue by AndreyNovik1993** [monitoringartist/grafana-aws-cloudwatch-dashboards#109]

**Comment by SchnitzelKopf** [comment]
+1

**Comment by k2glyph** [comment]
+1

**Comment by youngpabl0** [comment]
[AWS DynamoDB-1672251392082.txt](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/files/10315720/AWS.DynamoDB-1672251392082.txt)
hi all, i make a little dashboard for myself, take it like base if u want guyz
