### ISSUE TITLE
Data is not showing in AWS Billing Grafana Panel

### ISSUE THREAD

**Issue by ravi7248** [monitoringartist/grafana-aws-cloudwatch-dashboards#112]
I have tried the AWS billing dashboard template but no data is showing on the panels.
I have attached the policies to the user whose credentials are used in the data source mentioned in this (https://grafana.com/docs/grafana/next/datasources/aws-cloudwatch/).
Can anyone explain what's going wrong? Why I am not able to see any AWS billing metrics in the panel?

**Comment by jangaraj** [comment]
Of course, you need to have billing metrics already in the Cloudwatch - only then you will see billing data in the dashboard. 
I would say it is out of the scope of dashboarding how to get those data into CloudWatch. Please contact your AWS support - blind guess "Enable Billing Alerts Monitoring".
