### ISSUE TITLE
EC2 Dashboard stopped working. 

### ISSUE THREAD

**Issue by sunny5055** [monitoringartist/grafana-aws-cloudwatch-dashboards#113]
EC2 dashboard was working  ( using IAM user ) Suddenly stopped working 

Mainly its not able to pull out the tags which the dashboard template has. 

Object { error: "metric request error: \"InvalidParameter: 1 validation error(s) found.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[0].MetricStat.Metric.Dimensions[0].Value.\\n\"" }

unexpected error failed to call ec2:DescribeInstances, MissingParameter: The request must contain the parameter InstanceId
	status code: 400, request id: 86e0c6de-375a-4d2f-b2b6-7c744392c946null

Anyone else have the same issue?  

Further digging looks like this issue is purely related to filter for Instance Name and Instance ID.

**Comment by KRJNK** [comment]
I have the exact same issue, looks like something is wrong with filter {"tag:Name": ["$instancename"]}.

**Comment by sunny5055** [comment]
> I have the exact same issue, looks like something is wrong with filter {"tag:Name": ["$instancename"]}.

Exactly. this filter does not seem to work.

**Comment by jangaraj** [comment]
Could you try to create dashboard from the scratch, please? I have seen that sometimes migration to new dashboard model doesn't work very well (Grafana 8.x). I will be helpfull also if you report your Grafana version.

**Comment by sunny5055** [comment]
> Could you try to create dashboard from the scratch, please? I have seen that sometimes migration to new dashboard model doesn't work very well (Grafana 8.x). I will be helpfull also if you report your Grafana version.

There was no migration done. It suddenly stopped working with existing version. 
I have tried to create freshly create a new dashboard with import numerous times, it still has the same issue. 
Grafana v8.5.1

**Comment by jangaraj** [comment]
Could you enable Grafana debug logs and provide Grafana logs, pls?

**Comment by KRJNK** [comment]
I have updated Grafana from 8.5.0 to 8.5.1 and suddenly it started working. Apparently it was a known issue
https://github.com/grafana/grafana/releases/tag/v8.5.1

**Comment by sunny5055** [comment]
> Could you enable Grafana debug logs and provide Grafana logs, pls?

Sorry My version was 8.5.0 and i just updated to 8.5.1 and it resolved the issue.  Please mark this as closed.

**Comment by jangaraj** [comment]
Great. Thank you for the confirmation.
