### ISSUE TITLE
[AWS EC2] Template variables are not supported in alert queries

### ISSUE THREAD

**Issue by dmitrykinakh** [monitoringartist/grafana-aws-cloudwatch-dashboards#115]
After importing https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/master/aws-ec2/aws-ec2.json I would like to add several alerts so when, for example, CPUUtilization will be higher than, for example, than 50% I'll receive an email.
![image](https://user-images.githubusercontent.com/8025637/179221739-60293fad-f9cb-4cc3-8f2a-6d50bd9fc458.png)
Could you help me figure out what I'm missing? I'm a newbie in this.

**Comment by jangaraj** [comment]
This is not an issue of the dashboard, so it is out of scope for this repo. I recommend to create own dashboard and don't use any dashboard variables in the queries there.
