### ISSUE TITLE
why do you use SQS

### ISSUE THREAD

**Issue by HoangNgo88** [monitoringartist/grafana-aws-cloudwatch-dashboards#116]
Hi, I am reading your project and I love this project
I have a question, why do you choose SQS in your project instead of others like RabbitMQ or Kafka, are there any special features but others dont have it. Can you share me it. I am wondering when I should choose SQS instead of others like RabbitMQ or Kafka

**Comment by jangaraj** [comment]
Sorry, your issue is not an issue, but only a question.
