### ISSUE TITLE
AWS EC2 Dashboard

### ISSUE THREAD

**Issue by mineo-reitz** [monitoringartist/grafana-aws-cloudwatch-dashboards#118]
Hello,

Im running 32 EC2 instances. But in the "Tag Name" dropdown only show the instances that are named. Any tips on how to by pass and filter only by instance ID?

Thank you!!

**Comment by jangaraj** [comment]
This is more/less support ticket for your particular use case. I'm closing it. Tip: https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/4ecd084023fefcb148937a8be3f914df793ef664/aws-ec2/aws-ec2.json#L1981
