### ISSUE TITLE
bug(aws-rds): `VolumeIdleTime` metric not available in `AWS/RDS` namespace

### ISSUE THREAD

**Issue by rohankmr414** [monitoringartist/grafana-aws-cloudwatch-dashboards#119]
There are multiple overrides for `VolumeIdleTime` in the RDS dashboard, this metric is not present in the `AWS/RDS` namespace and also not being queried anywhere in the dashboard

https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/b6d68860300b8efcee46e1be21855dec21f71c07/aws-rds/aws-rds.json#L94-L97

**Comment by jangaraj** [comment]
Yes, I agree. Those are there because I copy dashboards and duplicate panels to have some consistency between dashboards/panels. I guess those are artefacts from EBS dasboard. Could you create a pull request, which will remove them, please?

**Comment by rohankmr414** [comment]
@jangaraj should I also migrate the dashboard panels from graph to timeseries visaulization type?

**Comment by jangaraj** [comment]
Yes, feel free to migrate panels to standard timeseries panel.
