### ISSUE TITLE
GetMetricStatisticsInput.Dimensions[0].Value Error in all MonitoringArtist dashboards

### ISSUE THREAD

**Issue by thiyaga123** [monitoringartist/grafana-aws-cloudwatch-dashboards#12]
Hi
It seems aws has updated their API. All of the monitoring Artist dashboards return below error when initializing. 
Grafana Version : Grafana v4.4.1

`
InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.`

**Comment by jangaraj** [comment]
I'm not sure. It looks like a problem of your config. See #13. Another user is able to use them in 4.4.1 version.

**Comment by egarbi** [comment]
I have also those in my logs, however Im still able to see the graph:
```t=2017-07-24T12:44:58+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/5 status=500 remote_addr=86.160.188.63 time_ms=133 size=36 referer="https://status.lebara.io/dashboard/db/aws-elb-classic-load-balancer?orgId=1"
t=2017-07-24T12:44:58+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"
t=2017-07-24T12:44:58+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/5 status=500 remote_addr=86.160.188.63 time_ms=57 size=36 referer="https://status.lebara.io/dashboard/db/aws-elb-classic-load-balancer?orgId=1"```

**Comment by egarbi** [comment]
This is not an issue with the Dashboard itself. It's related to templates returning empty variables.
In my case above I can see those errors with any region different than Ireland. That's expected since I don't have any ELB set for those regions.
Similar to this one https://github.com/grafana/grafana/issues/8676.

**Comment by jangaraj** [comment]
Closing.

Manually tested with my Docker image `monitoringartist/grafana-xxl:4.4` and I don't see that reported problem. You may see these errors:
```
t=2017-07-25T19:59:36+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1 status=500 remote_addr=192.168.32.1 time_ms=168 size=36 referer="http://192.168.32.133:3000/dashboard/db/aws-elb-classic-load-balancer?orgId=1"
t=2017-07-25T19:59:36+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, GetMetricStatisticsInput.Dimensions[0].Value.\n"
```
after dashboard import, when template variables are empty. Just choose right template variable value and it should be ok.
