### ISSUE TITLE
Spurious dimension in Cognito dashboard

### ISSUE THREAD

**Issue by sr-rossanderson** [monitoringartist/grafana-aws-cloudwatch-dashboards#121]
The Cognito definition has a random API dimension in the userpoolclient variable - until removed userpoolclients are not populated correctly.

Line 950 and 957 currently have :

"dimension_values($region,AWS/ApiGateway,Count,Stage, {\"ApiName\": \"$apiname\"})\ndimension_values($region,AWS/Cognito,SignInSuccesses,UserPoolClient,{\"UserPool\": \"$userpool\"})",

and should be:

"dimension_values($region,AWS/Cognito,SignInSuccesses,UserPoolClient,{\"UserPool\": \"$userpool\"})",

**Comment by jangaraj** [comment]
Thank you for the report. Could you create a pull request to fix it, please? I'm happy to merge it.

**Comment by jangaraj** [comment]
Fixed by PR #122
