### ISSUE TITLE
URLs outdated & Graph Panel Deprecated (AngularJS)

### ISSUE THREAD

**Issue by swiffer** [monitoringartist/grafana-aws-cloudwatch-dashboards#124]
Hi - thanks providing these dashboards!

I noticed links in the footer of the Dashboards are no longer working as Grafana changed their URL Structure:

https://grafana.com/grafana/dashboards/593-aws-lambda/

Their are several older Dashboards still using the Grafana Graph Panel which is Deprecated / Replaced by Time Series. Will these be updated / republished with a new version?

**Comment by jangaraj** [comment]
Thank you Matthias. Yes, I usually update dashboards as I'm updating them in my work. But it will be awesome if you can create PR for it. BTW also AWS has changed CloudWatch doc links while ago, so that one may also need an update.

**Comment by jplspotter** [comment]
Hi, by changing the panel type from graph to timeseries the deprecation is removed.
