### ISSUE TITLE
aws auto scaling dashboard issue

### ISSUE THREAD

**Issue by contact2rames** [monitoringartist/grafana-aws-cloudwatch-dashboards#125]
Hello,
I have imported dashboard 617 in to grafana , it is giving errors. Could you please help me?

https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/tree/master/aws-autoscaling

**Errors:**
Object
status:400
statusText:"Bad Request"
data:Object
results:Object
config:Object
method:"POST"
url:"api/ds/query"
data:Object
headers:Object
retry:0
hideFromInspector:false
message:"metric request error: \"InvalidParameter: 8 validation error(s) found.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[0].MetricStat.Metric.Dimensions[0].Value.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[1].MetricStat.Metric.Dimensions[0].Value.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[2].MetricStat.Metric.Dimensions[0].Value.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[3].MetricStat.Metric.Dimensions[0].Value.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[4].MetricStat.Metric.Dimensions[0].Value.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[5].MetricStat.Metric.Dimensions[0].Value.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[6].MetricStat.Metric.Dimensions[0].Value.\\n- minimum field size of 1, GetMetricDataInput.MetricDataQueries[7].MetricStat.Metric.Dimensions[0].Value.\\n\""
![AWSAutoScaling_Dashboard_Error](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/assets/121218331/c9bc1f96-2678-499d-b2c0-a83dcb829ab2)

Screenshot attached for reference.

**Comment by jangaraj** [comment]
See README:
> Please set your dashboard variables (Region, ...) after dashboard import. Empty dashboard variables are reason of initial "Unable to call AWS API" or "Metric request error" error.

**Comment by contact2rames** [comment]
Thanks for quick response Jan Garaj.

I already have variables set for region,datasource. Still i am seeing issue.



[image: image.png]
Thanks
Ramesh

**Comment by jangaraj** [comment]
That looks like a problem with your Grafana/CloudWatch config. Unfortunately, that Grafana/CloudWatch config is out of the scope for this repo.
