### ISSUE TITLE
aws-ebs need to add average Throughput and average number of IOPS graphs

### ISSUE THREAD

**Issue by fradee** [monitoringartist/grafana-aws-cloudwatch-dashboards#127]
Please add to "aws-ebs" dashboard calculation of average Throughput and average number of IOPS according to AWS recommendation: https://repost.aws/knowledge-center/ebs-cloudwatch-metrics-throughput-iops

**Comment by jangaraj** [comment]
Sure, could you create PR, please?

**Comment by fradee** [comment]
> Sure, could you create PR, please?

There is: https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/pull/128
