### ISSUE TITLE
Multiple Lambda metrics not working with this code - aws-lambda/aws-lambda.json

### ISSUE THREAD

**Issue by yashaswi90** [monitoringartist/grafana-aws-cloudwatch-dashboards#130]
The code that you mentioned in the aws-lambda is not working if we have more than one lambda,
Could you please let me know is there anything else that I need to do in your code.
aws-lambda/aws-lambda.json

**Comment by jangaraj** [comment]
What is not working? There is dashboard variable, where you select which Lambda do you want to visualise when you have more than one Lambda:
![obrázok](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/assets/1182932/6d08a6a6-7133-496a-be6f-d939fa273f15)

**Comment by yashaswi90** [comment]
Could you please let me know like is there anything different need to do for multiple lambda, I used the code that you provided and in templating list I have added both the function name in options parameter. 

It is giving error
 **Templating
Templating init failed Cannot create property 'selected' on string 'ondemand-telemetry-data-services-pre-processor'**

<{
          "allValue": null,
          "current": {},
          "datasource": "$datasource",
          "definition": "dimension_values($region,AWS/Lambda,Duration,FunctionName)",
          "hide": 0,
          "includeAll": false,
          "label": "FunctionName",
          "multi": false,
          "name": "functionname",
          "options": [
            "lambda-processor-1",
            "lambda-processor-2"
          ],
          "query": "dimension_values($region,AWS/Lambda,Duration,FunctionName)",
          "refresh": 1,
          "regex": "",
          "skipUrlSync": false,
          "sort": 1,
          "tagValuesQuery": "",
          "tags": [],
          "tagsQuery": "",
          "type": "query",
          "useTags": false
        }>

**Comment by yashaswi90** [comment]
Could you please provide sample like where you are saying I have provided both the lambda function name in the options field.
Is there any other place where we need to configure for multiple lambda, as with the existing code it is not showing multiple lambda in the dropdown.

**Comment by jangaraj** [comment]
You don't need to edit dashboard - Lambda names are discovered from your real CloudWatch data. Of course Grafana must have proper permissions to access CW metrics. So I really don't understand what is wrong. You didn't provide reproducible example.

**Comment by yashaswi90** [comment]
> You don't need to edit dashboard - Lambda names are discovered from your real CloudWatch data. Of course Grafana must have proper permissions to access CW metrics. So I really don't understand what is wrong. You didn't provide reproducible example.

Ok , Got it. Thanks . Closing this ticket.
