### ISSUE TITLE
Metrics are empty after import

### ISSUE THREAD

**Issue by gil-davidovitz** [monitoringartist/grafana-aws-cloudwatch-dashboards#133]
Hi, All the metrics are empty after importing the AWS billing dashabord. I'm using Grafana 10, and have cost metrics in Cloudwatch.
What am i missing ?

<img width="357" alt="image" src="https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/assets/103889751/853fcef0-674a-49b1-9c14-b6a5b992fba7">

**Comment by jangaraj** [comment]
Please provide reproducible example of your issue.
