### ISSUE TITLE
Tag Filtering

### ISSUE THREAD

**Issue by prsf1233** [monitoringartist/grafana-aws-cloudwatch-dashboards#14]
Hi Jan, as discussed I would like to implement tag filtering on the AWS-EC2 dashboard. My end users do not know the InstanceId of their environment but I do tag each instance with a friendly name. I would like to be able to use the Name Tag for selecting the graphs rather than the InstanceId but so far have not been able to make it work. I can see the Tags but not been able to get the correct syntax.

![image](https://user-images.githubusercontent.com/14126600/29208930-fcb04932-7e83-11e7-8787-dee6957b46c6.png)

![image](https://user-images.githubusercontent.com/14126600/29208953-082d7820-7e84-11e7-85b4-40e43948ae4f.png)

Any suggestion on whether this is possible?

**Comment by jangaraj** [comment]
Thank you for idea and example. Tag filtering will be useful definitely. Let me investigate and test it.

**Comment by jangaraj** [comment]
There will be visualization problem with `ec2_instance_attribute($region, Tags, {})` if EC2 instance has more than 1 tag, example:
![image](https://user-images.githubusercontent.com/1182932/29212839-69fb8448-7e98-11e7-870d-add3dfc1ceaa.png)

I would like to have 1st variable (query) which will return all tags keys and then 2nd variable (query), which will return tags values based on selected tag key (1st variable). Is it possible?

Probably we need to wait for https://github.com/grafana/grafana/pull/8307

**Comment by prsf1233** [comment]
Cool, for my use case only one Tag exists but yes I am sure others would need to filter on multple.

**Comment by paco3346** [comment]
@prsf1233 Check out my comment on that PR: https://github.com/grafana/grafana/pull/8307#issuecomment-322515481

This is how I handle the 'friendly name' issue internally.

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/ec2-tag-filtering/aws-ec2/aws-ec2-tag-filtering.json - EC2 dashboard with tag name filtering for Grafana 4.5.beta1+. Feel free to improve this dashboard.

**Comment by pax-awitt** [comment]
hi @jangaraj, i wanted to submit a branch and pr for this issue, but i obviously get a 403.  how can i do this?

**Comment by jangaraj** [comment]
Hi @pax-awitt, that's correct. You can push the code only to the repos, where you have write permission.  Please [fork this repo](https://help.github.com/articles/fork-a-repo/) first and then [create the pull request](https://help.github.com/articles/about-pull-requests/) based on your forked and modified repo. [Github help](https://help.github.com) can be the useful doc for you.

**Comment by tomislater** [comment]
What about something like that: `ec2_instance_attribute($region, Tags.Name, {})`. I have checked it on `4.6.0` version.

**Comment by jangaraj** [comment]
@tomislater That's filtering is by one tag key (_Name_). It's OK for simple tagging. But it can be more complicated. For example, if you have blue/green deployment. Then the _Name_ tag value is not unique and you need to filter by additional key (_Colour_) as well. The best general solution for the dashboard is to have ad-hoc filters similar to Elasticsearch ad-hoc filters:
![elk-adhoc-filter](https://user-images.githubusercontent.com/1182932/32132250-e2d726be-bbc0-11e7-9843-eb21f7f58b97.gif)
Feel free to open feature/pull request for CloudWatch plugin. Some function, which will return all available tag keys and tag values in the selected AWS "space" (ec2, ebs, emr, ...) must be implemented.

**Comment by jangaraj** [comment]
Grafana 5 EC2 dashboard with name tag filtering https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/commit/b9259241b665fec42830f252b1a73344ad17ef8e:

![image](https://user-images.githubusercontent.com/1182932/40502465-f6da993c-5f82-11e8-8dcc-7194b90781cf.png)

If EC2 instances don't have a Name tags, then `Tag Name: All` and use classic `Instance ID` variable to select instance.

**Comment by saindia-TBA** [comment]
Hi,

We have imported latest change done by you but still not working.

![image](https://user-images.githubusercontent.com/12527789/40575000-8e773480-60fa-11e8-9093-cd8dfafa47d2.png)

**Comment by jangaraj** [comment]
It looks like a IAM problem in your case. Do you have:

 "ec2:DescribeTags", "ec2:DescribeInstances"
