### ISSUE TITLE
SES visualization defaults are "weird" for low-traffic environments

### ISSUE THREAD

**Issue by ankon** [monitoringartist/grafana-aws-cloudwatch-dashboards#16]
For the 'Send/Delivery' graph the dashboard suggests to _average_ the values from cloudwatch, and then connect things using _lines_. This leads to really odd graphs with low amounts of emails being sent, where most data points are either 0 or 1. 

I've now switched to '_sum_ the values, and then render _bars_', which gives a better overview in my situation.

**Comment by jangaraj** [comment]
Could you create PR with your better SES dashboard please? It'll be awesome if you can add also screenshot. Thanks.

**Comment by jangaraj** [comment]
No user response.
