### ISSUE TITLE
README.md - please add quote around the 

### ISSUE THREAD

**Issue by strus38** [monitoringartist/grafana-aws-cloudwatch-dashboards#21]
Hi

The current example script to import the dashboard does not support space char in the password. Please put quote around the $grafana_cred variable to avoid this issue.

`
j=$(curl -s -k -u "$grafana_cred" $grafana_host/api/gnet/dashboards/$d | jq .json)

curl -s -k -u "$grafana_cred" -XPOST -H "Accept: application/json" \
`

Thanks.

**Comment by jangaraj** [comment]
Good point. Fixed. Thank you.
