### ISSUE TITLE
EC2 to Cloudwatch? 

### ISSUE THREAD

**Issue by emilnarvz** [monitoringartist/grafana-aws-cloudwatch-dashboards#24]
Hi Jan, thanks for your posts. Im starting with Grafana and CloudWatch, I have a little confusion. 

Im have dashboards created in Grafana with ElasticSearch as datasource, but now I need to move all that dashboards to Cloudwatch because I want to create alarms. I see your codes here, but im not clearly sure what Im doing. How I can do this?

I will appreciate if you can help me with this. 

:/

**Comment by jangaraj** [comment]
This is not a specific issue with dashboards included in this project. It looks like a request for Grafana support. Please use https://community.grafana.com/

**Comment by emilnarvz** [comment]
Im sorry. Thanks!
