### ISSUE TITLE
aws ecs service stats receive no data points

### ISSUE THREAD

**Issue by Datise** [monitoringartist/grafana-aws-cloudwatch-dashboards#29]
I've been having a problem with the cloudwatch browser where I can't seem to get ecs service metrics to return data points. All the other ecs cluster metrics work normally and I've verified the services have metrics in cloudwatch. The request response all seem fine to me: 
![my request response](https://user-images.githubusercontent.com/7938814/36750661-f9007baa-1bb2-11e8-8025-3969b4470376.png)

I've verfied with AWS that there's nothing on the cloudwatch side and that my permissions are appropriate. They questioningly attempted to help by proposing the use of a GET not a POST request but as the structure works fine for other ECS metrics I'm hesitant. Has anyone seen or faced this recently? It's incredibly annoying to need the console for a very small amount of important metrics >.<.

**Comment by jangaraj** [comment]
Did you use correct dimension or combination of dimensions - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html?

**Comment by Datise** [comment]
Yes but 10 minutes ago it just loaded data points so I'm just going to write this off as bug in the matrix. Thanks anyway!
