### ISSUE TITLE
AWS/EC2 dashboard issue 

### ISSUE THREAD

**Issue by OleksandrSlobodian** [monitoringartist/grafana-aws-cloudwatch-dashboards#3]
Issue with getting InstanceId
Grafana logs:
```
t=2016-11-01T16:14:31+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="InvalidParameter: 1 validation errors:\n- field too short, minimum length 1: Dimensions[0].Value"
t=2016-11-01T16:14:31+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1 status=500 remote_addr=195.160.233.233 time_ns=0 size=36
```
```
t=2016-11-01T16:13:01+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="MissingParameter: The request must contain the parameter InstanceId\n\tstatus code: 400, request id: "
t=2016-11-01T16:13:01+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1 status=500 remote_addr=195.160.233.233 time_ns=241ns size=36
```
Grafana v3.1.1 (commit: a4d2708)

**Comment by jangaraj** [comment]
You have to specify values for all dimensions - select which instanceId stat you want to see.

**Comment by OleksandrSlobodian** [comment]
Hi againe when I told there is an issue with getting InstanceId I was meant that 

```
"query": "ec2_instance_attribute($region, InstanceId, {})",
```

return nothing to InstanceId array 
![aws ec2](https://cloud.githubusercontent.com/assets/12740635/19920851/c9c5dbfa-a0e3-11e6-86ae-f63c430e5673.png)

**Comment by jangaraj** [comment]
So you don't have any instances in region us-east-1. If you have, then your cloudwatch datasource is not configured properly -> please follow official doc http://docs.grafana.org/datasources/cloudwatch/

**Comment by dominikhahn** [comment]
Works for me:
![aws-ec2-dashboard](https://cloud.githubusercontent.com/assets/12954090/19923165/730f69d6-a0e6-11e6-817e-d8afdfd6fc59.jpg)

Grafana v4.0.0-pre1 (commit: 578507a)

**Comment by OleksandrSlobodian** [comment]
Guys, have no clue what is the root cause of my issue, but I found workeraund - getting InstanceId array with other query:

```
dimension_values($region, AWS/EC2, CPUUtilization, InstanceId)
```

![aws ec2 work](https://cloud.githubusercontent.com/assets/12740635/19938174/a88705e2-a12c-11e6-8b56-c2d4e32b16ca.png)

**Comment by jangaraj** [comment]
Do you have a problem with `ec2_instance_attribute($region, InstanceId, {})` ?

**Comment by OleksandrSlobodian** [comment]
yes - correct

**Comment by jangaraj** [comment]
So I guess, you don't have EC2 permissions (for `ec2_instance_attribute`) and you have only cloudwatch permissions (`dimension_values`).

**Comment by OleksandrSlobodian** [comment]
So do I need more permissions than

```
 "cloudwatch:GetMetricData",
 "cloudwatch:GetMetricStatistics",
 "cloudwatch:ListMetrics"
```

**Comment by jangaraj** [comment]
`ec2_instance_attribute` uses probably **EC2 DescribeInstances**, so you need additional **EC2** permissions (not only cloudwacth). I don't know which one - please dig into cloudwatch source code, add full EC2 read only, pay for commercial support, ....

**Comment by OleksandrSlobodian** [comment]
hm - thanks for advise - will dig this issue... and thank you so much for great dashboards! ... sorry for making issue in this project :|

**Comment by jangaraj** [comment]
It'll be awesome if you create pull request with minimal required grafana IAM policy - your start point can be https://gist.github.com/jangaraj/109ebf581d1fb74d9082cca617e9eda5. Thanks.
