### ISSUE TITLE
Can you patch Custom Namespaces provided by AWS?

### ISSUE THREAD

**Issue by Moon-Tae-Kwon** [monitoringartist/grafana-aws-cloudwatch-dashboards#30]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/send_logs_to_cwl_instances.html#ec2-configuration-cwl

thank you
I write well

**Comment by jangaraj** [comment]
I think this is not a right project for your request. Please use Grafana project or read doc http://docs.grafana.org/features/datasources/cloudwatch/ - there is already option to use custom namespaces.
