### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by erwinsetiawan** [monitoringartist/grafana-aws-cloudwatch-dashboards#31]
I'm getting this error 

runtime error: invalid memory address or nil pointer dereference

with grafana iam access policy

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "autoscaling:Describe*",
                "cloudwatch:Describe*",
                "cloudwatch:Get*",
                "cloudwatch:List*",
                "logs:Get*",
                "logs:List*",
                "logs:Describe*",
                "logs:TestMetricFilter",
                "sns:Get*",
                "sns:List*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}

**Comment by jangaraj** [comment]
It's not an issue of a dashboard. It's Grafana issue - probably https://github.com/grafana/grafana/issues/10733
