### ISSUE TITLE
Auto scaling Issue

### ISSUE THREAD

**Issue by rayl15** [monitoringartist/grafana-aws-cloudwatch-dashboards#32]
I imported the autoscaling dashboard. Selected the us-east-1 region and by side of auto scaling  group it has a drop down with "None" I think the autoscaling group is not getting populated

**Comment by jangaraj** [comment]
I need more info. I don't have autoscaling metrics in my cloudwatch, so I can't verify it. Maybe:
```
ec2_instance_attribute($region, AutoScalingGroupName, {})
```
can provide AutoScalingGroupName values.

**Comment by jangaraj** [comment]
Closing, no user input.
