### ISSUE TITLE
Problems displaying Cloudfront data

### ISSUE THREAD

**Issue by ricardclau** [monitoringartist/grafana-aws-cloudwatch-dashboards#4]
Hi!

I was trying to use your dashboard to visualise Cloudfront data but there must be some permissions I am missing as Grafana is not able to get the DistributionId of our website

At the moment, the EC2 instance has an IAM role with this policy

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "cloudwatch:GetMetricStatistics",
        "cloudwatch:ListMetrics"
      ],
      "Effect": "Allow",
      "Resource": "*"    
    }
  ]
}
```

Is anything else needed for Cloudfront?

**Comment by ricardclau** [comment]
I have even tried to add temporarily

```
cloudfront:*
```

but it did not do the trick. Maybe this is related to Cloudfront being a global service with no actual region? What do you use the region for in your dashboard?

Anyway, help will be much appreciated!

**Comment by jangaraj** [comment]
Unfortunately I don't use cloudfront. You can start with https://gist.github.com/jangaraj/109ebf581d1fb74d9082cca617e9eda5 policy or try to contact your AWS support.

**Comment by jangaraj** [comment]
http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cf-metricscollected.html
There is used region "Global".

**Comment by ricardclau** [comment]
Yeah I also noticed that... so any way your dashboard would not work as there is a template variable called region which is effectively a list of AWS regions, not "Global"

Will ask in the grafana project and keep you posted

**Comment by jangaraj** [comment]
OK, please fix it and contribute back (pull request). Thx.

**Comment by jangaraj** [comment]
Closing, no user response.

**Comment by andrewmcgilvray** [comment]
To fix this dashboard just replace the region template variable with "us-east-1". CloudFront metrics are only ever in us-east-1.

**Comment by jangaraj** [comment]
Could you create pull request, which will fix this problem please? Thanks!
