### ISSUE TITLE
Templating init failed

### ISSUE THREAD

**Issue by jweyrich** [monitoringartist/grafana-aws-cloudwatch-dashboards#40]
Hello! I just tried to use the dashboard with our CW datasource, but got the following error:

> Templating init failed
> Metric request error

Screenshot:

![image](https://user-images.githubusercontent.com/206930/44482083-db66a600-a61d-11e8-837b-329bd94b5464.png)

The JavaScript console reveals a request failed with error 500 (a bug in Grafana itself?):

> angular.js:12759 POST http://52.67.43.249:3000/api/tsdb/query 500 (Internal Server Error)

Details:
- Running Grafana v5.2.2 (aeaf7b2);
- The access key I'm using in the CW datasource is from a IAM user that has an associated role with full read-only permission on the account.

Any ideas?

**Comment by jangaraj** [comment]
Which dashboard?

Maybe:
- incorrect dashboard variable values
- problem with used IAM policy
....

**Comment by jweyrich** [comment]
I just installed/imported the dashboard. So there are no customizations, and no variables. I just imported and selected the CW datasource.
The IAM policy should be fine since I'm using the same datasource in another EC2 dashboard (one I created myself), and the EC2 metrics are pulled and presented correctly.

**Comment by jangaraj** [comment]
README:

> Please set your dashboard variables (Region, ...) after dashboard import. Empty dashboard variables are reason of initial "Unable to call AWS API" error.

**Comment by jweyrich** [comment]
Hmm, ok. So that's my fault. Thank you.
I have another dashboards with region/cluster/service/etc variables, and they don't give me this error even when empty. They only show empty dashboards.
But thanks, that was indeed the point you said.
