### ISSUE TITLE
Filter All AWS Resources by Tags

### ISSUE THREAD

**Issue by mjallday** [monitoringartist/grafana-aws-cloudwatch-dashboards#41]
Similar to #14.

When you create some resources in AWS (e.g. EB applications) it's impossible to control the naming. You can however control the tagging. 

Given this it's very useful to be able to filter all resources by tags similar to how we do EC2 filtering.

**Comment by jangaraj** [comment]
Yes, you are right. Unfortunately this funcionality is not supported by CloudWatch datasource at the moment, so it can't be implemented.
