### ISSUE TITLE
Restrict to one region

### ISSUE THREAD

**Issue by r-divakaran-hrs** [monitoringartist/grafana-aws-cloudwatch-dashboards#45]
Hello,

First of all thanks for all these dashboards. They are working very well.

I am using most of them. One thing that I would like to ask is how can I by default select one region. For example in https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/master/aws-elb/aws-elb-classic-lb.json I would like eu-west-1 to be always selected.

Could you please guide here !?

**Comment by jangaraj** [comment]
Don't use a variable for the region, but use directly 'eu-west-1' string in your panels.
