### ISSUE TITLE
[Question] EC2 memory by CloudWatch

### ISSUE THREAD

**Issue by zakabluk** [monitoringartist/grafana-aws-cloudwatch-dashboards#47]
Hi! Do you are going to add support  illustration memory for EC2 when use script mon-put-instance-data.pl 
 for collecting more metrics? Like memory, it's vary important point.
AWS doc: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html

**Comment by jangaraj** [comment]
Unfortunately, I don't have a plan to create any dashboard with custom metrics, only standard metrics.
