### ISSUE TITLE
not able to get multi value selected in variables (tag filtering)

### ISSUE THREAD

**Issue by meet101** [monitoringartist/grafana-aws-cloudwatch-dashboards#48]
Hi, For EC2 dasboard, I am trying to get multiple instances CPU graph in one panel. I can do this with instance id. but can't do with any other tags like instance name. in default EC2 dashboard, has variables instance name and instance id with single value selection and based on it we can populate the graph for that specific instance. in my case, I want to have more then one instances graph in one panel and I want to filter out based on instance name not instance id. 

I am able to get multi instances graph if i use only instance id variable by enabling multi-value selection. this works only if I remove instance name variables. In this scenario my variables looks like,  

$region | regions() 
$InstanceId | ec2_instance_attribute($region, InstanceId, {})

now, if I need to figure out how to get instance name and replace it with instance id. I tried multiple options. didn't work. 
can anyone help me here? I am thinking it's issue because when we select multiple values for specific variable, grafana is not able to parse it properly. do I need regex for this?

Thanks in advance!

**Comment by jangaraj** [comment]
Sorry, support for customization is not in the scope of this project. Your question should be posted to https://community.grafana.com. Please search there and on Grafana GitHub for similar issues.
