### ISSUE TITLE
Is there any way to monitor ec2 memory usage by CloudWatch ?

### ISSUE THREAD

**Issue by gtzinos** [monitoringartist/grafana-aws-cloudwatch-dashboards#49]

**Comment by jangaraj** [comment]
Hi George, your question is not in the scope of this project. 
Please read Cloudwatch doc: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html

**Comment by gtzinos** [comment]
Hello @jangaraj, thank you very much!
