### ISSUE TITLE
Display ec2 instance tag/tags

### ISSUE THREAD

**Issue by gytisgreitai** [monitoringartist/grafana-aws-cloudwatch-dashboards#5]
Hi,

first - thanks! Really cool dashboards. 
Is there any way I could display tags from an instance in ec2 dashboard?
I've tried to use Templating with:
`ec2_instance_attribute($region,Tags, {"instance-id": ["$instanceid"]})`
but this returns a JSON array, and grafana simply displays this as [Object Object]. I cannot apply regex to it and extract only the Value I want, because internally grafana also treats this a a json array and tries to apply Regex not on a string representation but on the array itself

Thanks!

**Comment by jangaraj** [comment]
Unfortunately your problem is not in the scope of this project. It's a question for cloudwatch datasource developers -> Raintank. Try http://slack.raintank.io/
