### ISSUE TITLE
Metrics query failures on AWS / EC2 dashboard if not using EC2 "Name" tags

### ISSUE THREAD

**Issue by mdurn** [monitoringartist/grafana-aws-cloudwatch-dashboards#50]
Perhaps this should just be in the readme, but it looks like if an AWS account does not make use of "Name" Tags for EC2 (e.g. all of my EC2 instances have a blank Name since we use other custom tags), then queries that rely on the $instancename variable will fail. Once I changed the variables to use our custom tags, the queries worked. I wouldn't expect custom tags to be in the scope of this project, but it might be helpful to mention in the readme that this can be an issue.

This was with Grafana 5.3.4. Not sure if this is a grafana issue with the queries as well?

Other than that, thanks for the dashboard!

**Comment by jangaraj** [comment]
Thanks Michael, your concerns are valid. Proper EC2 deployments use more advance tags, such as `Region, Zone, Colour, Env, Stack, App, ...`, not just `Name`. 

The challenge here is how to make a generic and human-friendly dashboard for all tag cases. Unfortunately, Grafana is not able to generate a list of available tags, so it can't be offered as additional variable `Tag used for filtering` in the dashboard. So tag `Name` is "hardcoded" in the dashboard + it is mentioned in the variable label explicitly as `Tag Name` + list of Instance IDs which depends on the tag Name is also visible for the user.

Almost no one reads the readme. So, any improvements must be done on the dashboard level. Feel free to create PR with generic improvement (maybe better variable label, dashboard description, ...).
