### ISSUE TITLE
Can't apply default region

### ISSUE THREAD

**Issue by SckyzO** [monitoringartist/grafana-aws-cloudwatch-dashboards#52]
Hello

First of all thanks for all these dashboards. They are working very well.

I have a question. How can force panel to use only eu-west-1.
I have set my region to eu-west-1 in cloudwatch plugin but when i use your dashboard, default region is ap-northest-1

Regard,

**Comment by jangaraj** [comment]
Select `eu-west-1` region in the dashboard and then save dashboard, but check "Save current variables":
![image](https://user-images.githubusercontent.com/1182932/51257842-6fa42180-19a0-11e9-8249-7224a8fc6f33.png)
