### ISSUE TITLE
No data from17th Jan

### ISSUE THREAD

**Issue by philo123** [monitoringartist/grafana-aws-cloudwatch-dashboards#53]
Hello,

I am not receiving any data since Jan 17th 2019. Billing Alerts is turned on under Billing > Preferences > Receive Billing Alerts.  I also have these reports sent to my S3 bucket too. 

I am able to see the reports under S3 bucket but my Grafana is not getting updated. Am I missing something?

**Comment by jangaraj** [comment]
Billing dashboard uses Cloudwatch billing metrics, not a metrics from S3 reports. If you don't see them, then you may have a problem with your connection/permissions/etc. I don't see a problem with dashboard.

**Comment by philo123** [comment]
I dont think I have permission issues as I am able to test the connection successfully.

![image](https://user-images.githubusercontent.com/45512337/52229229-70aedb80-28da-11e9-906b-5f5335e535da.png)

**Comment by jangaraj** [comment]
Sure, but there still can be million problems with IAM, resource granularity permissions, etc. And all of these problem are problem with AWS configuration, not with provided Grafana dashboard => they are not in the scope of support of this project. 

Please read Grafana doc http://docs.grafana.org/features/datasources/cloudwatch/, contact your AWS support and ask them for help with the problem.

**Comment by philo123** [comment]
Thanks for the guidance.
