### ISSUE TITLE
Billing details for a particular instance

### ISSUE THREAD

**Issue by philo123** [monitoringartist/grafana-aws-cloudwatch-dashboards#54]
Hi,

Is there a way I can filter out the total cost including the data transfer, space util, and other resources consumed that are charged me for a particular instance? 
for ex: I have p2.Xlarge instance...and with its corresponding instance ID, can all pull the report of how much in total it has costed me?

Thanks in Advance.

**Comment by jangaraj** [comment]
No.

**Comment by philo123** [comment]
Thanks for the quick reply. 

Is this feature worth asking for? Can this be considered one?

**Comment by jangaraj** [comment]
No, resource granularity is not provided by Cloudwatch. Each dashboard has a link to AWS doc - please visit their doc and you will see what is available.
