### ISSUE TITLE
How to add Credit details too in Billing Dashboard?

### ISSUE THREAD

**Issue by philo123** [monitoringartist/grafana-aws-cloudwatch-dashboards#56]
Hello,

I have few credits that I am currently using in AWS and so My billing dashboard shows 0 amount...is there a way we can track even the Credits? as to what resources is consuming how much of our credits and once all the credits are over, then automatically, we can see our billing

**Comment by jangaraj** [comment]
I'm sorry, this is Grafana configuration problem and Grafana support is not in the scope of this project. Please use official documentation to learn more about available options - http://docs.grafana.org/
