### ISSUE TITLE
Is it possible to generate dashboards for multiple AWS accounts?

### ISSUE THREAD

**Issue by rustyguts** [monitoringartist/grafana-aws-cloudwatch-dashboards#58]
The bash loop in the readme.md works fine when adding dashboards for a single account. How could I modify that loop so that I can generate a dashboard for each AWS account I have?

**Comment by jangaraj** [comment]
Unfortunately, you are asking for bash support, which is not in the scope of this project. Please find some bash doc. Personally, I don't recommend to create copy of dashboard for each AWS account. Better option will be dashboard variable ([type datasource](http://docs.grafana.org/reference/templating/#variable-types)), which will offer used dashboard datasource, so you will have just one dashboard for all AWS accounts.
