### ISSUE TITLE
Not showing all regions AWS EC2

### ISSUE THREAD

**Issue by prasenforu** [monitoringartist/grafana-aws-cloudwatch-dashboards#6]
Recently I started using Grafana for AWS, using Grafana Docker version.

Noticing that in Cloudwatch Datasource its updated All regions, 
But rest EC2,S3,RDS Dashboard its not showing all regions. 

in above dashboard its missing regions, us-east-2 & ap-south-1

Please find attachment for your reference.

![image](https://cloud.githubusercontent.com/assets/19322497/21712450/e757e46e-d41a-11e6-97b2-99c507a7dbf4.png)

**Comment by jangaraj** [comment]
That's probably a datasource issue, not a dashboard issue. Dashboard utilizes only methods, which are provided by datasource (for example `regions()` to get list of regions). Correct project for this issue is https://github.com/grafana/grafana.

**Comment by prasenforu** [comment]
If its datasource issue why its showing in Datasource Regions

**Comment by jangaraj** [comment]
Because list of regions is hardcoced there - https://github.com/grafana/grafana/blob/c97131d1a0fa9e1ed6456b124294259812b21c53/public/app/plugins/datasource/cloudwatch/partials/config.html#L42

**Comment by prasenforu** [comment]
you can see us-east-2 & ap-south-1 is there and if its hard coded then it should fetch same in EC2 and others as well, not sure from where its fetching the data ?

**Comment by prasenforu** [comment]
Looks like got the problem, your json file not fetching data from here (https://github.com/grafana/grafana/blob/c97131d1a0fa9e1ed6456b124294259812b21c53/public/app/plugins/datasource/cloudwatch/partials/config.html#L42)

basically its fetching data from pkg/api/cloudwatch/metric.go where missing regions, us-east-2 & ap-south-1 :)

Anyway thanks for prompt reply.

**Comment by jangaraj** [comment]
No, datasource config uses hardcoded values, but templating (`regions()` function) uses some AWS API function (probably EC2/DescribeRegions). Please don't waste my time and ask cloudwatch datasource code owner your questions. I don't own that code, I'm not developer of cloudwatch datasource. I can dig into your problem, but it will be paid service (BTW: also GrafanaLabs offers paid support).
