### ISSUE TITLE
ELB RequestCount should use Sum statistic rather than Average

### ISSUE THREAD

**Issue by cippaciong** [monitoringartist/grafana-aws-cloudwatch-dashboards#62]
Hello, first of all thank you for your work on these dashboards and for sharing them.
I was looking at the Application ELB dashboard and noticed that in the RequestCount / Latency panel you are using the [`Average`](https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/bb2a3baa1fa65037f18dba8d04d941bfcc0401c6/aws-elb/aws-elb-application-lb.json#L133) statistic for ELB RequestCount.

According to [AWS Documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html) the most useful statistic should be `Sum` and I think that `Minimum`, `Maximum`, and `Average` always return 1 or 0. 

**Edit**: Actually the same holds for other metrics in the ELB Dashboard like all http code counts, connection counts and so on

**Comment by jangaraj** [comment]
Thank you for the feedback. Could you create pull request to fix reported problem, please?

**Comment by ronnysha** [comment]
י ^ יףמ 
ע
0


.
