### ISSUE TITLE
Lambda function name filtering using regex

### ISSUE THREAD

**Issue by orfeu65** [monitoringartist/grafana-aws-cloudwatch-dashboards#70]
Hi Jan!
In the AWS Lambda dashboard, is there the possibility to create and use variables for part of the functionName?
For example, I have functions like serviceA-test-functionZ, serviceA-test-functionY and I would like to get the graph for 
* all the functions having a name like serviceA-*  
* or the functions having a name like serviceA-* AND like *-test-*
I created the variables adding regex to your functionName variable, but now I cannot find the way to use these variables in the queries. Is it possible?
Thanks!

**Comment by jangaraj** [comment]
Sorry, this is request for Grafana CloudWatch support, which is out of the scope of this project. Please use https://community.grafana.com/
