### ISSUE TITLE
Add support for ComputeSavingsPlans in AWS/Billing

### ISSUE THREAD

**Issue by christoph-buente** [monitoringartist/grafana-aws-cloudwatch-dashboards#71]
We subscribed to a ComputeSavingsPlan and the total amount charged without any corresponding graph showing where those elevated costs occured. Then i found out cloudwatch supports an additional Dimension for AWS/Billing called `ComputeSavingsPlans`.

**Comment by jangaraj** [comment]
Question is how make generic billing dashboard, which will be useful for user with/without `ComputeSavingsPlan`?

**Comment by christoph-buente** [comment]
It is just yet another query. If there are no costs on that dimension, there is simply no graph. Like with any other Billing Dimension
    
    {
    	"alias": "{{ServiceName}}",
    	"dimensions": {
    		"Currency": "USD",
    		"ServiceName": "ComputeSavingsPlans"
    	},
    	"expression": "",
    	"highResolution": false,
    	"id": "",
    	"metricName": "EstimatedCharges",
    	"namespace": "AWS/Billing",
    	"period": "",
    	"refId": "AO",
    	"region": "us-east-1",
    	"returnData": false,
    	"statistics": [
    		"Average"
    	]
    }

**Comment by jangaraj** [comment]
LGTM. Could you create pull request, please?
