### ISSUE TITLE
AWS Cloudwatch Browser

### ISSUE THREAD

**Issue by Moulick** [monitoringartist/grafana-aws-cloudwatch-dashboards#74]
Hi,
The AWS Cloudwatch Browser does not work completely
If I select anything other then broker wide metrics like CPU, it does not work

![Screenshot 2020-04-30 at 3 54 10 PM](https://user-images.githubusercontent.com/15780903/80700156-d77d6d80-8afa-11ea-9fbe-1780d43b6b09.png)

The same selection works on cloudwatch itself.

**Comment by jangaraj** [comment]
Could you provide exact example with cloudwath console screenshot, please? 

Are you aware of note in the documentation panel?

**Comment by Moulick** [comment]
![Screenshot 2020-04-30 at 4 46 27 PM](https://user-images.githubusercontent.com/15780903/80704415-267ad100-8b02-11ea-941a-54a52a5c7fae.png)

I think I am missing the note, can you please link me? :)

**Comment by Moulick** [comment]
like in the cloudwatch query there is a selection for broker, that unfortunately does not show up in the grafana

**Comment by jangaraj** [comment]
![image](https://user-images.githubusercontent.com/1182932/80707952-1e636700-8aeb-11ea-9e4c-2732c96ee68a.png)
![image](https://user-images.githubusercontent.com/1182932/80707982-2de2b000-8aeb-11ea-96a2-03acff3990f4.png)
This looks like this case, 2 dimensions are used `Broker` AND `Queue`. So this metric needs 2 dimensions to appears in the Grafana. But there is no way how to create generic browser dashboard which will be working with 0 AND 1 AND 1+ dimensions metrics.
