### ISSUE TITLE
Default Jason file imported - error - InvalidParameter: 1 validation error(s) found

### ISSUE THREAD

**Issue by Kirandp6** [monitoringartist/grafana-aws-cloudwatch-dashboards#75]
Hi, 
I have AWS EC2 instance running in us-east-2 ,  i have grafana working , i imported the EC2 dashboard as is

Created the policy as mentioned in https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards

Imported all per the script in same page 

Not very clean what is meaning of 

"Please set your dashboard variables (Region, ...) after dashboard import"

Is that from The UI of the grafana ?  If yes then i tried that 

, then from UI also tried to change the region, but i see below err 

InvalidParameter: 1 validation error(s) found. - minimum field size of 1, GetMetricDataInput.MetricDataQueries[0].MetricStat.Metric.Dimensions[0].Value.
Object
status:400
statusText:"Bad Request"
data:Object
results:Object
message:"InvalidParameter: 1 validation error(s) found. - minimum field size of 1, GetMetricDataInput.MetricDataQueries[0].MetricStat.Metric.Dimensions[0].Value. "
message:"InvalidParameter: 1 validation error(s) found. - minimum field size of 1, GetMetricDataInput.MetricDataQueries[0].MetricStat.Metric.Dimensions[0].Value. "

#######################################

Please suggest 

==

I am using 
[root@vm01 ~]# grafana-server -v
Version 7.0.0 (commit: aee1438ff2, branch: HEAD)
[root@vm01 ~]#

On centos 7 VM 

==

![image](https://user-images.githubusercontent.com/51837573/82776841-1dc7a300-9e01-11ea-8e98-2c1e5f635b4e.png)

**Comment by Kirandp6** [comment]
![image](https://user-images.githubusercontent.com/51837573/82776915-5a939a00-9e01-11ea-805e-6daf2033e3f0.png)

**Comment by jangaraj** [comment]
Obviously you need to have populated variables properly and then you will see data. Now you are selectin `None` instance, which of course return unexpected data from the CloudWatch:
![image](https://user-images.githubusercontent.com/1182932/82786261-901d9f00-9e64-11ea-96c7-72187af85f56.png)

**Comment by Kirandp6** [comment]
FYI in my case only working drop downs are the 1st 2, BTW the test datastore works fine per the above screen shots, Please suggest if i am doing anything wrong 

![image](https://user-images.githubusercontent.com/51837573/82844284-d25ed480-9e94-11ea-8b94-f66ef8b5357b.png)

**Comment by Kirandp6** [comment]
eg 

![image](https://user-images.githubusercontent.com/51837573/82844876-089d5380-9e97-11ea-9135-51003b53f702.png)

**Comment by jangaraj** [comment]
Dashboard itself is working fine for many people. That means dashboard is OK and your configuration is wrong. Unfortunately, Grafana/CloudWatch configuration support is not in the scope of this repo. You may use https://community.grafana.com/ or contact your AWS support. Maybe you really don't have any EC2 instances in `us-east-1` region.
