### ISSUE TITLE
Feature: A way to import all AWS dashboards under a grafana folder

### ISSUE THREAD

**Issue by shubhamc183** [monitoringartist/grafana-aws-cloudwatch-dashboards#76]
Right now, automation exists in importing all the dashboards of this repo at once in Grafana. But what if someone wants to import all the dashboard under their Grafana but in a folder(say "AWS CloudWatch").

We add that functionality

`folderId=$(curl -s -k -u "$grafana_cred" $grafana_host/api/folders | jq '.[] | select(.title=="AWS CloudWatch").id')`

and pass this "folderId" in the payload of the dashboard import POST request only if the "folderID" is not empty.

If this make sense then I can send a PR.

Please, let me know.

**Comment by jangaraj** [comment]
Yes, it makes sense. Could you create PR, please? That script from the README `Import all Monitoring Artist AWS dashboards in one go (example script, bash/curl/jq required)` needs to be updated (for example input variables are not required anymore). Keep in mind that some users may not have folder `AWS CloudWatch`, so use root folder in that case. I would use variable also for that folder name. Thank you Shubham.

**Comment by shubhamc183** [comment]
Ok, I'll send a PR in which the input variable will be removed and the folder name check will be done.

**Comment by shubhamc183** [comment]
Added a PR: https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/pull/77
