### ISSUE TITLE
Creating alerts in Grafana dashboard 

### ISSUE THREAD

**Issue by robincher** [monitoringartist/grafana-aws-cloudwatch-dashboards#78]
Hi,

This is more of a question rather than bug. First-time user of grafana here.

I understand that it may not be that straight-forward to create alerts via grafana dashboard, so would like to check if anyone did some workaround on it?

Currently, whenever i want to edit an existing panel of a dashboard, i'll get ```Template variables are not supported in alert queries``` this specific message.

Robin

**Comment by jangaraj** [comment]
This is not a question for this project. Here is not a free Grafana&AWS support, because project is related to Grafana and AWS. Please read doc https://grafana.com/docs/grafana/latest/alerting/ or ask community for help https://community.grafana.com/ .

**Comment by robincher** [comment]
ok sure just close this issue. 

I am not thinking it as a free aws support also. Appreciate your guide to the relevant sites.
