### ISSUE TITLE
aws-cognito

### ISSUE THREAD

**Issue by ksanjay7** [monitoringartist/grafana-aws-cloudwatch-dashboards#79]
Hi,
Could you point me for any sample template for aws-cognito

Regards, Sanjay

**Comment by jangaraj** [comment]
Unfortunately, I don't have. But feel free to create pull request for the dashboard created from the official CloudWatch doc: https://docs.aws.amazon.com/cognito/latest/developerguide/monitoring-available-cw-metrics.html

**Comment by ksanjay7** [comment]
Hi Jan,
I started working on the skeleton of it and I'm bit of struck where the account cognito id details are not getting populated with below template and would like to ask for your help if I'm missing something.

Appreciate any help on this.

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "description": "Visualize AWS Cognito metrics",
  "editable": true,
  "gnetId": 575,
  "graphTooltip": 0,
  "id": 146,
  "iteration": 1595651819316,
  "links": [],
  "panels": [],
  "refresh": false,
  "schemaVersion": 25,
  "style": "dark",
  "tags": [
    "monitoringartist",
    "cloudwatch"
  ],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": "CloudWatch",
          "value": "CloudWatch"
        },
        "hide": 0,
        "includeAll": false,
        "label": "Datasource",
        "multi": false,
        "name": "datasource",
        "options": [],
        "query": "cloudwatch",
        "queryValue": "",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      },
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "us-east-1",
          "value": "us-east-1"
        },
        "datasource": "$datasource",
        "definition": "regions()",
        "hide": 0,
        "includeAll": false,
        "label": "Region",
        "multi": false,
        "name": "region",
        "options": [],
        "query": "regions()",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "allValue": null,
        "current": {
          "isNone": true,
          "selected": false,
          "text": "None",
          "value": ""
        },
        "datasource": "$datasource",
        "definition": "dimension_values($region,AWS/Cognito,UserPoolId,UserPoolClient)",
        "hide": 0,
        "includeAll": false,
        "label": "Cognito",
        "multi": false,
        "name": "cognito",
        "options": [],
        "query": "dimension_values($region,AWS/Cognito,UserPoolId,UserPoolClient)",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-30d",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "AWS Cognito",
  "uid": "AWSCognito",
  "version": 1
}
```

**Comment by jangaraj** [comment]
Doc is your friend: https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/

> dimension_values(region, namespace, metric, dimension_key, [filters])

Yours:
```
dimension_values($region,AWS/Cognito,UserPoolId,UserPoolClient)
```
region -> `$region` - OK
namespace -> `AWS/Cognito` - OK
metric - `UserPoolId` - it doesn't look like a valid metric - https://docs.aws.amazon.com/cognito/latest/developerguide/monitoring-available-cw-metrics.html - I would try `SignInSuccesses`
dimension_key - `UserPoolClient` - OK (if you want to list UserPoolClients)

This is not a free CloudWatch/Grafana support, so these kind of task are really not in the scope. This is a issue tracker for existing dashboards in the repo. Please use community support, your AWS/Grafana support for the development. Of course feel free to create PR with your Cognito dashboard at the end, so it will be available for the community.

Thanks.

**Comment by ksanjay7** [comment]
Thanks  Jan.. This worked like charm..

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "description": "Visualize AWS Cognito metrics",
  "editable": true,
  "gnetId": 575,
  "graphTooltip": 0,
  "id": 146,
  "iteration": 1595651819316,
  "links": [],
  "panels": [],
  "refresh": false,
  "schemaVersion": 25,
  "style": "dark",
  "tags": [
    "monitoringartist",
    "cloudwatch"
  ],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": "CloudWatch",
          "value": "CloudWatch"
        },
        "hide": 0,
        "includeAll": false,
        "label": "Datasource",
        "multi": false,
        "name": "datasource",
        "options": [],
        "query": "cloudwatch",
        "queryValue": "",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      },
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "us-east-1",
          "value": "us-east-1"
        },
        "datasource": "$datasource",
        "definition": "regions()",
        "hide": 0,
        "includeAll": false,
        "label": "Region",
        "multi": false,
        "name": "region",
        "options": [],
        "query": "regions()",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "allValue": null,
        "current": {
          "isNone": true,
          "selected": false,
          "text": "None",
          "value": ""
        },
        "datasource": "$datasource",
        "definition": "dimension_values($region,AWS/Cognito, SignInSuccesses,UserPoolClient)",
        "hide": 0,
        "includeAll": false,
        "label": "Cognito",
        "multi": false,
        "name": "cognito",
        "options": [],
        "query": "dimension_values($region,AWS/Cognito, SignInSuccesses,UserPoolClient)",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-30d",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "AWS Cognito",
  "uid": "AWSCognito",
  "version": 1
}

I'm working on building general cognito metrics and also advanced security metrics for cognito (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-viewing-advanced-security-metrics.html) and will raise PR soon.

**Comment by dan-vidoni** [comment]
@ksanjay7 did you manage to get the Cognito SignIn / SignUp metrics into the dashboard ?

**Comment by ksanjay7** [comment]
Yes Dan, I was able to create dashboard for SignUpSuccesses and SignInSuccesses and below are the metrics configuration.

{
          "alias": "",
          "dimensions": {
            "UserPool": "*",
            "UserPoolClient": "Admin"
          },
          "expression": "",
          "id": "",
          "matchExact": true,
          "metricName": "SignUpSuccesses",
          "namespace": "AWS/Cognito",
          "period": "",
          "refId": "A",
          "region": "$region",
          "statistics": [
            "Maximum"
          ]
        }


        {
          "alias": "",
          "dimensions": {
            "UserPool": "*",
            "UserPoolClient": "*"
          },
          "expression": "",
          "id": "",
          "matchExact": true,
          "metricName": "SignInSuccesses",
          "namespace": "AWS/Cognito",
          "period": "",
          "refId": "A",
          "region": "$region",
          "statistics": [
            "Average"
          ]
        }

**Comment by dan-vidoni** [comment]
could you share the full dashboard config? I don't know where to add these metrics as the cognito Signup/Signin metrics are not available in the metrics dropdown, only the advanced security metrics are present on my side. (I'm using grafana locally, installed from homebrew)

![Screenshot 2020-10-03 at 22 22 35](https://user-images.githubusercontent.com/10724432/95000142-f8c11900-05c6-11eb-841e-06de868af971.png)

**Comment by ksanjay7** [comment]
Hi Dan,

You would not have metric name populated which is same for me too, so I have to type SignUpSuccesses in Metrics and stats as Maximum, Dimension as UserPool = * and UserPoolClient = Admin

SignInSuccesses in Metrics and stats as Maximum, Dimension as UserPool = * and UserPoolClient = *

Hope it helps you :)

**Comment by jangaraj** [comment]
Cognito dashboard published - https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/commit/b8bf6da92370892527e1de05b73449cec72f1f49 feel free to test. Unfortunately, I don't have account where I can verify this cognito dashboard.

**Comment by dan-vidoni** [comment]
awesome guys, thanks a lot @ksanjay7  I started testing as I have some user pools, will come back with results

**Comment by dan-vidoni** [comment]
tested for signup signin and token refresh, the federation metrics I can't test as I don't have any federated users. 
thanks again @ksanjay7

**Comment by s1mrankaur** [comment]
@jangaraj I am able to select user pools in the select box.  I always see "None" for pool clients and IdentityProvider (which is okay).

But I am constantly seeing - Metric request error for all 4 graphs in cognito grafana template. How can I fix this?

Metric request error
Object
status:500
statusText:""
data:Object
message:"Metric request error"
config:Object
method:"POST"
url:"api/ds/query"
data:Object
retry:0
headers:Object
hideFromInspector:false
message:"Metric request error"

**Comment by jangaraj** [comment]
Grafana logs provide more details about Cloudwatch request errors usually.
