### ISSUE TITLE
No datapoint on AWS Billing

### ISSUE THREAD

**Issue by magnetogit** [monitoringartist/grafana-aws-cloudwatch-dashboards#8]
Hi 
What the policy use with AWS Billing ? ,I see No datapoint after install dashboard ,also ec2/rds rds dashboard is working
Thanks.

**Comment by jangaraj** [comment]
1. ) Minimal should be:
```
{
  "Version": "2012-10-17",
  "Statement":[{
      "Effect":"Allow",
      "Action":["cloudwatch:GetMetricStatistics","cloudwatch:ListMetrics"],
      "Resource":"*",
         }
      }
   ]
}
```
Some items (for example ec type, tags, ...) may need also additional policy rules.
2.) Try to use full admin role to see if it's a problem with your policy
3.) Try to use browser https://grafana.net/dashboards/590, to see metrics available in billing namespace.
4.) Try to use browser console to see datasource request and any errors in the datasource response.

And finally contribute back and update README with minimal and maximal policy, which will be useful for all users.

Thanks!

**Comment by tylux** [comment]
Had the same problem here, our fix was to ensure Receive Billing Alerts was turned on under Billing > Preferences > Receive Billing Alerts.

We also used the following policy CloudWatchReadOnlyAccess
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "autoscaling:Describe*",
        "cloudwatch:Describe*",
        "cloudwatch:Get*",
        "cloudwatch:List*",
        "logs:Get*",
        "logs:Describe*",
        "logs:TestMetricFilter",
        "sns:Get*",
        "sns:List*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

**Comment by magnetogit** [comment]
Thank you jangaraj & tylux

I think my problem effect from
![screen shot 2560-01-27 at 11 12 51 am](https://cloud.githubusercontent.com/assets/21017375/22360452/715bac46-e482-11e6-9835-0ee6d6e1434f.png)

Because after i change  metric region from ap-southeast-1 to us-east-1 , Billing dashboard can receive data

![screen shot 2560-01-27 at 11 17 08 am](https://cloud.githubusercontent.com/assets/21017375/22360521/066b9d46-e483-11e6-9f8a-7ef3a7dc4bae.png)

**Comment by markschwarz** [comment]
Turning on alerts made Cloudwatch metrics available for me, too.  Thanks for the tip!

**Comment by maiorano84** [comment]
Also confirmed here: Turning on alerts enabled Estimated Billing metrics available for us as well
