### ISSUE TITLE
EC2 and SNS  import json Error " Template variables could not be initialized: Metric request error"

### ISSUE THREAD

**Issue by Venkata-Maddineni** [monitoringartist/grafana-aws-cloudwatch-dashboards#85]
I'm facing this error while importing the EC2 and SNS JSON and it is not working, could you please help me on this?

**EC2 :** 
![image](https://user-images.githubusercontent.com/67999564/93979398-e959f880-fd9a-11ea-8506-374b11b68c3a.png)

**SNS:** 
![image](https://user-images.githubusercontent.com/67999564/93980219-fa573980-fd9b-11ea-82cb-0dac1eade24a.png)

NOTE:  AWS lambda , AWS SQS, AWS logs, billing , etc these are working without any issue . I'm facing a problem with ec2 and SNS import.

**Comment by jangaraj** [comment]
I would recommend to read readme:

> Please set your dashboard variables (Region, ...) after dashboard import. Empty dashboard variables are reason of initial "Unable to call AWS API" or "Metric request error" error.
