### ISSUE TITLE
Please create Grafana Dashboard for AWS WAF

### ISSUE THREAD

**Issue by satish-chef** [monitoringartist/grafana-aws-cloudwatch-dashboards#86]
Hello,

Please create Grafana dashboard for AWS WAF - https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html#waf-metrics

**Comment by exequielrafaela** [comment]
This will be really useful since WAF both v1 and v2 are a very widespread AWS security solution.

CC: @diego-ojeda-binbash @lgallard @angelofenoglio

**Comment by jangaraj** [comment]
Please check https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/tree/aws-waf/aws-waf improve and create pull request with better version of that dashboard. It needs someone who has good WAF metrics in the CloudWatch and knowledge what can be useful to visualize.
