### ISSUE TITLE
aws-ec2 - Metric request error

### ISSUE THREAD

**Issue by LegionSports** [monitoringartist/grafana-aws-cloudwatch-dashboards#89]
I imported aws-ec2_rev4.json and when I check out the dashboard, I'm presented with the following error and none of the graphs show any data: 

```
Templating [volumeid]
Error updating options: Metric request error
```

![image](https://user-images.githubusercontent.com/67813130/100637801-4923d100-3301-11eb-955a-da5b92a50b8d.png)

Could someone point me in the right direction?

**Comment by jangaraj** [comment]
See readme - https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards :
> Please set your dashboard variables (Region, ...) after dashboard import. Empty dashboard variables are reason of initial "Unable to call AWS API" or "Metric request error" error.

**Comment by LegionSports** [comment]
I set my region (us-east-1) and am still getting the error. 

Anything else I can look at?

**Comment by jangaraj** [comment]
All variables must have correct value, mot just region.
