### ISSUE TITLE
ECS default setting has dimension "ServiceName": "$service"

### ISSUE THREAD

**Issue by AnthonyWC** [monitoringartist/grafana-aws-cloudwatch-dashboards#9]
I noticed that ECS dashboard (https://grafana.net/dashboards/551) has ServiceName defined under targets by default, which causes API request to fail for CPU & Memory utilization.

Default should remove:
"ServiceName": "$service"
from dimensions for CPU & Memory.

**Comment by jangaraj** [comment]
Hi Anthony, could you make a pull request to fix this problem please?

**Comment by jangaraj** [comment]
Fixed in #10
