### ISSUE TITLE
Feature: ElasticCache CPU Utilization (Percent) and Database Memory Usage Percentage (Percent) 

### ISSUE THREAD

**Issue by shubhamc183** [monitoringartist/grafana-aws-cloudwatch-dashboards#93]
I want to send a PR to implement panels for the below-mentioned metrics in ElasticCache Dashboard.

1. CPU Utilization (Percent)
2. Database Memory Usage Percentage (Percent)

**Comment by jangaraj** [comment]
Sure, go ahead. IMHO CPU utilization is already there on the node level - https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/blob/master/aws-elasticache/aws-elasticache-redis.png

**Comment by jangaraj** [comment]
Thank you. Resolved by your PR.
